<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GtaDe.Definitions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GtaDe.SaveFormat\GtaDe.SaveFormat.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\**\*.json" />
  </ItemGroup>

</Project>
